# Generated by Django 4.2.14 on 2024-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_desciption_listing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='new_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
