# Generated by Django 4.2.14 on 2024-07-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='listings',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listings')},
        ),
    ]
