# Generated by Django 4.2.14 on 2024-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_user_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='user_watchlist', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(related_name='user_listings', to='auctions.listing'),
        ),
    ]
