# Generated by Django 4.2.14 on 2024-07-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_user_watchlist_alter_user_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
