# Generated by Django 4.2.14 on 2024-07-26 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_last_bid_listing_you_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='last_bid',
            field=models.ManyToManyField(blank=True, null=True, related_name='last_bid_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
