# Generated by Django 4.2.14 on 2024-07-26 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_last_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='last_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='last_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_bid_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
